server:
  port: 9090
  
spring:
  application:
    name:  API-GATEWAY-SERVICE
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user/**
          - id: TASK-SERVICE
            uri: lb://TASK-SERVICE
            predicates:
              - Path=/task/**
  zipkin:
    sampler:
      probabilistic:
        rate: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
