server:
  port: 9092

spring:
  application:
    name:  TASK-SERVICE
  datasource:
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_task_mgmt?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  zipkin:
    sampler:
      probabilistic:
        rate: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


logging:
  level:
    root: INFO
