server:
  port: 8761
spring:
  application:
    name: EUREKA-REGISTRY-SERVICE
  zipkin:
    sampler:
      probabilistic:
        rate: 1
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost
