server:
  port: 9091
  
spring:
  application:
    name:  USER-SERVICE
  zipkin:
    sampler:
      probabilistic:
        rate: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
